---
- name: Setup Django
  hosts: prem
  become: yes
  gather_facts: no

  tasks:
    - name: Install Python and pip
      package:
        name:
          - python3
          - python3-pip
          - pip install --upgrade pip
          - pip3 install pipenv

        state: present


    - name: Install project dependencies with pipenv
      command: pipenv install
      args:
        chdir: /home/premsagar/pro-ansible/Pipfile

    - name: Run Django server
      command: pipenv run python manage.py runserver
      
